#app build
FROM node:latest AS build-stage
WORKDIR /client
COPY /frontend/package*.json /client/
RUN npm install
COPY /frontend /client
RUN npm run build

RUN mkdir app
RUN cp -r dist/* app/

FROM nginx:stable
COPY --from=build-stage /client/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
    





